# Run with:
# docker compose -f docker/compose.yaml up --build
# Enter the container with:
# docker exec -it borg-isaac-gr00t bash
services:
  borg-isaac-gr00t:
    image: borg-isaac-gr00t
    container_name: borg-isaac-gr00t
    build:
      context: ../
      dockerfile: docker/base.Dockerfile
    runtime: nvidia
    network_mode: host

    volumes:
      - ../:/workspace

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
              - gpu
              - utility
              - compute
              - video 

    entrypoint: bash
    stdin_open: true
    tty: true